name: 'Mention external collaborators'
description: 'Gather all external collaborators and mention them on an issue'
inputs:
  GitHub_Token:  # id of input
    description: 'token to authenticate with GitHub'
    required: false
    default: ${{ github.token }}
outputs:
  comment_id:
    description: 'The comment id'
runs:
  using: 'node12'
  main: 'dist/index.js'
